owner: pandalabuptime
repo: uptime
user-agent: uptime/github
skipDescriptionUpdate: true
skipTopicsUpdate: true

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "* * * * *"

commitMessages:
  commitAuthorName: 'PandaLab Uptime'
  commitAuthorEmail: 'tech+uptime@pandalab.fr'

sites:
  - { name: 'Website', url: https://www.pandalab.fr }
  - { name: 'Status', url: https://status.pandalab.fr }
  - { name: 'CDN', url: https://cdn.pandalab.fr }
