owner: pandalabuptime
repo: uptime
user-agent: uptime/github
skipDescriptionUpdate: true
skipTopicsUpdate: true
skipHomepageUpdate: true

status-website:
  publish: false
  
commitMessages:
  commitAuthorName: 'PandaLab Uptime'
  commitAuthorEmail: 'tech+uptime@pandalab.fr'

sites:
  - { name: 'Website', url: https://www.pandalab.fr }
  - { name: 'Status', url: https://status.pandalab.fr }
  - { name: 'CDN', url: https://cdn.pandalab.fr }
  - { name: 'Test #A1', url: https://expired.badssl.com }
  - { name: 'Test #A2', url: https://idonotexist.net }
