owner: pandalabuptime
repo: uptime
user-agent: uptime/github
skipDescriptionUpdate: true
skipTopicsUpdate: true
skipHomepageUpdate: true

sites:
  - { name: 'Website', url: https://www.pandalab.fr }
  - { name: 'Status', url: https://status.pandalab.fr }
  - { name: 'CDN', url: https://cdn.pandalab.fr }

status-website:
  publish: false
